### COSNT
@userId=dXNlcjAxQGV4YW1wbGUuY29t
@tokenId=dXNlcjAxQGV4YW1wbGUuY29t.c0edfd0ff5b10ed8fc051b019d89b296.5c957bda951e3eaf4f1a5d46c2037690d83ca7e18047deb54f06df8e35b7eb59


### NOT FOUND
POST https://localhost:3001/ping?foo=bar

{
  "foo": "bar"
}

### GET
GET https://localhost:3001/customers?id={{userId}}
Authorization: Bearer {{tokenId}}


### DELETE
DELETE https://localhost:3001/customers?id={{userId}}
Authorization: Bearer {{tokenId}}


### POST /tokens
POST https://localhost:3001/tokens

{
  "email": "user01@example.com",
  "password": "abcd1234..."
}

### POST /customers
POST https://localhost:3001/customers

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "user03@example.com",
  "password": "abcd1234...",
  "tosAgreement": true
}

### GET /tokens
GET https://localhost:3001/tokens?id={{tokenId}}

### PUT /customers
PUT https://localhost:3001/customers
Authorization: Bearer {{tokenId}}

{
  "email": "user10@example.com",
  "firstName": "Johny"
}


### GET
GET https://localhost:3001/menus
Authorization: Bearer {{tokenId}}
