### COSNT
@userId=ef15c030aaadaab90e9773a2f9e3cc5596515f26424d664fd3b5f1dfc74759d0
@tokenId=ef15c030aaadaab90e9773a2f9e3cc5596515f26424d664fd3b5f1dfc74759d0.0b60559c9b4761023aa5523d1a8fb9cb.8ba41af6ae37af4277ea934ba1f65795e66d96a1d9ad17963d48bc0acf0526d5


### NOT FOUND
POST https://localhost:3001/ping?foo=bar

{
  "foo": "bar"
}

### GET
GET https://localhost:3001/customers?id={{userId}}
token: {{tokenId}}


### DELETE
DELETE https://localhost:3001/customers?id={{userId}}
token: {{tokenId}}


### POST /tokens
POST https://localhost:3001/tokens

{
  "email": "user8@example.com",
  "password": "abcd123"
}

### POST /customers
POST https://localhost:3001/customers

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "user11@example.com",
  "password": "abcd123",
  "tosAgreement": true
}

### GET /customers
GET https://localhost:3001/customers?id={{userId}}
token: {{tokenId}}

### PUT /customers
PUT https://localhost:3001/customers
token: {{tokenId}}

{
  "email": "user10@example.com",
  "firstName": "Johny"
}
