### COSNT
@userId=7f1ffad9787995a14ba79f26643fe32485de882edef63e952141185eff26ccb9
@tokenId=7f1ffad9787995a14ba79f26643fe32485de882edef63e952141185eff26ccb9.072d67c789da65590fab0a3af411a0d7.a6eb240cf5bb02d173b21cefb274907da1465640bc88eb220a4b8d1c147c9088


### NOT FOUND
POST https://localhost:3001/ping?foo=bar

{
  "foo": "bar"
}

### GET
GET https://localhost:3001/customers?id={{userId}}
Authorization: Bearer {{tokenId}}


### DELETE
DELETE https://localhost:3001/customers?id={{userId}}
Authorization: Bearer {{tokenId}}


### POST /tokens
POST https://localhost:3001/tokens

{
  "email": "user02@example.com",
  "password": "abcd1234..."
}

### POST /customers
POST https://localhost:3001/customers

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "user03@example.com",
  "password": "abcd1234...",
  "tosAgreement": true
}

### GET /tokens
GET https://localhost:3001/tokens?id={{tokenId}}

### PUT /customers
PUT https://localhost:3001/customers
Authorization: Bearer {{tokenId}}

{
  "email": "user10@example.com",
  "firstName": "Johny"
}
